- dbscripts/cmpdb.sql
- deploy-chainmap.sh
- routes/challenge.js
- routes/login.js
- routes/questionBoard.js
- stopNode.sh
This is the Pull request to enable testing server to be run.
> changes to setup test server

- app.js
- node_modules/md5/.npmignore
- node_modules/md5/.travis.yml
- node_modules/md5/LICENSE
- node_modules/md5/README.md
- node_modules/md5/md5.js
- node_modules/md5/package.json
- node_modules/md5/test.js
- routes/challenge.js
- routes/index.js
- routes/login.js
- routes/questionBoard.js
- routes/users.js
- views/partials/footer.ejs
- views/partials/nav_menu.ejs
- views/questionBoard.ejs
- views/questionDetails.ejs
uploaded all the files that are necessary for the challengeboard and user registration
> challengeboard module and the user registration

- .gitignore
- routes/index.js
- routes/login.js
- routes/questionBoard.js
- routes/users.js
Check in the env specific Db settings
> changes for global variables

- routes/index.js
- routes/login.js
- routes/users.js
- views/askQuestion.ejs
- views/error.ejs
- views/loginRegister.ejs
- views/partials/header_login.ejs
"error page fix + more validation
> error page fix + more validation

- routes/index.js
- routes/questionBoard.js
- routes/users.js
- views/partials/body_header.ejs
- views/questionBoard.ejs
- views/questionDetails.ejs
- views/userProfile.ejs
> User profile done

- views/partials/body_footer.ejs
- views/userProfile.ejs
> some clean up

- views/partials/header_login.ejs
> register extra alert remove

- routes/index.js
- routes/trainingMaterial.js
- views/partials/body_header.ejs
- views/trainingMaterial.ejs
> training materials

- deploy-ss1-tar.sh
- routes/index.js
- routes/questionBoard.js
- views/loginRegister.ejs
> George 6 29 fix1

- views/askQuestion.ejs
- views/home.ejs
- views/partials/body_header.ejs
- views/questionBoard.ejs
- views/trainingMaterial.ejs
> changes for home page etc.

- .gitignore
- app.js
- routes/index.js
- routes/login.js
- routes/questionBoard.js
- routes/trainingMaterial.js
- routes/users.js
simply moved db confs out of code.
Also every routes files can be use global connection object of mysql. This way use less memory.
> Envoirments files

- views/userProfile.ejs
> user profile error for allansweredquestions

- app.js
- env/local-deploy.js.sample
- libs/UserBalanceService.js
balance checking every 20 second if no balance checked in 1 day or a new user
> balance check fix for system

- public/css/style.css
- routes/index.js
- smart-contract/cmap-smart-contract.js.mainnet
- smart-contract/cmap-smart-contract.js.testnet
- views/aboutUs.ejs
- views/home.ejs
- views/partials/header_login.ejs
- views/trainingMaterial.ejs
UI changes for training
And a lot more.
> Gz V2.0 check-in

- public/js/custom.js
- routes/users.js
- views/partials/header_login.ejs
Re: [chainmaporg/cmp] Profile Bug (#98)  Fixed
> Re: [chainmaporg/cmp] Profile Bug (#98)

- views/questionBoard.ejs
- views/questionDetails.ejs
> Fixed formatting issues, replaced non-breaking spaces with regular space.

- views/home.ejs
> Hide rest of time stamp

- dbscripts/fixBrozen(needed only once).sql
- views/askQuestion.ejs
> Fixed brozen to bronze

- dbscripts/cmpdb.sql
- routes/questionBoard.js
> Prevent multiple votes, allow changing vote direction (however, without new contract)

- routes/index.js
- routes/recommendations.js
- views/home.ejs
> Displays the Hottest Links

- views/home.ejs
If match fails, make sure summary is not null. Currently code checks for punctuation to find first sentence, and may fail if there is no punctuation. Hopefully this fixes that issue.
> checking if match fails

- routes/index.js
- routes/users.js
- views/partials/body_footer.ejs
- views/userProfile.ejs
- views/userSuggestions.ejs
> added suggested users page

- routes/index.js
- routes/users.js
- views/connectJobs.ejs
- views/userProfile.ejs
> Job Postings Page
